name: Gogol UI Push Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
    - name: Install modules
      run: yarn
    - name: Run Prettier
      run: yarn pretty