name: Gogol UI Storybook to Page Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment:
      name: github-pages
      url: $0
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        path: storybook-static
        build_command: npm run build-storybook