/* eslint-disable import/no-extraneous-dependencies */
import { css } from "@emotion/react";
import prefix from "./prefix";
import colors from "../theme/colors";
import { fontFamily } from "../theme/typography";
import { hexToHSL } from "../utils/colorConvert";

// css reboot
const styles = css`
@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Noto+Serif+JP:wght@700&display=swap");
    :root {
        --${prefix}blue: ${colors.lightMode.blue};
        --${prefix}indigo: ${colors.lightMode.indigo};
        --${prefix}purple: ${colors.lightMode.purple};
        --${prefix}pink: ${colors.lightMode.pink};
        --${prefix}red: ${colors.lightMode.red};
        --${prefix}orange: ${colors.lightMode.orange};
        --${prefix}yellow: ${colors.lightMode.yellow};
        --${prefix}green: ${colors.lightMode.green};
        --${prefix}teal: ${colors.lightMode.teal};
        --${prefix}cyan: ${colors.lightMode.cyan};
        --${prefix}black: ${colors.lightMode.black};
        --${prefix}white: ${colors.lightMode.white};
        --${prefix}gray: ${colors.lightMode.gray};
        --${prefix}gray-dark: ${colors.lightMode.grayDark};
        --${prefix}gray-100: ${colors.lightMode.gray100};
        --${prefix}gray-200: ${colors.lightMode.gray200};
        --${prefix}gray-300: ${colors.lightMode.gray300};
        --${prefix}gray-400: ${colors.lightMode.gray400};
        --${prefix}gray-500: ${colors.lightMode.gray500};
        --${prefix}gray-600: ${colors.lightMode.gray600};
        --${prefix}gray-700: ${colors.lightMode.gray700};
        --${prefix}gray-800: ${colors.lightMode.gray800};
        --${prefix}gray-900: ${colors.lightMode.gray900};
        --${prefix}primary: ${colors.lightMode.primary};
        --${prefix}primary-light: ${hexToHSL(colors.lightMode.primary, 40)};
        --${prefix}primary-dark: ${hexToHSL(colors.lightMode.primary, -7)};
        --${prefix}secondary: ${colors.lightMode.secondary};
        --${prefix}secondary-light: ${hexToHSL(colors.lightMode.secondary, 20)};
        --${prefix}secondary-dark: ${hexToHSL(colors.lightMode.secondary, -7)};
        --${prefix}success: ${colors.lightMode.success};
        --${prefix}success-light: ${hexToHSL(colors.lightMode.success, 40)};
        --${prefix}success-dark: ${hexToHSL(colors.lightMode.success, -7)};
        --${prefix}info: ${colors.lightMode.info};
        --${prefix}info-light: ${hexToHSL(colors.lightMode.info, 30)};
        --${prefix}info-dark: ${hexToHSL(colors.lightMode.info, -7)};
        --${prefix}warning: ${colors.lightMode.warning};
        --${prefix}warning-light: ${hexToHSL(colors.lightMode.warning, 30)};
        --${prefix}warning-dark: ${hexToHSL(colors.lightMode.warning, -7)};
        --${prefix}danger: ${colors.lightMode.danger};
        --${prefix}danger-light: ${hexToHSL(colors.lightMode.danger, 20)};
        --${prefix}danger-dark: ${hexToHSL(colors.lightMode.danger, -10)};
        --${prefix}light: ${colors.lightMode.light};
        --${prefix}light-light: ${hexToHSL(colors.lightMode.light, -10)};
        --${prefix}light-dark: ${hexToHSL(colors.lightMode.light, -7)};
        --${prefix}dark: ${colors.lightMode.dark};
        --${prefix}dark-light: ${hexToHSL(colors.lightMode.dark, 30)};
        --${prefix}dark-dark: ${hexToHSL(colors.lightMode.dark, -7)};
        --${prefix}primary-rgb: ${colors.lightMode.primaryRgb};
        --${prefix}secondary-rgb: ${colors.lightMode.secondaryRgb};
        --${prefix}success-rgb: ${colors.lightMode.successRgb};
        --${prefix}info-rgb: ${colors.lightMode.infoRgb};
        --${prefix}warning-rgb: ${colors.lightMode.warningRgb};
        --${prefix}danger-rgb: ${colors.lightMode.dangerRgb};
        --${prefix}light-rgb: ${colors.lightMode.lightRgb};
        --${prefix}dark-rgb: ${colors.lightMode.darkRgb};
        --${prefix}white-rgb: ${colors.lightMode.whiteRgb};
        --${prefix}black-rgb: ${colors.lightMode.blackRgb};
        --${prefix}body-color-rgb: ${colors.lightMode.bodyColorRgb};
        --${prefix}body-bg-rgb: ${colors.lightMode.bodyBgRgb};
        --${prefix}font-sans: ${fontFamily.body};
        --${prefix}font-serif: ${fontFamily.heading};
        --${prefix}font-monospace: SFMono-Regular, Menlo, Monaco, Consolas,
            "Liberation Mono", "Courier New", monospace;
        --${prefix}gradient: linear-gradient(
            180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0)
        );
        --${prefix}heading-font-family: var(--${prefix}font-serif);
        --${prefix}body-font-family: var(--${prefix}font-sans);
        --${prefix}body-font-size: 1rem;
        --${prefix}body-font-weight: 400;
        --${prefix}body-line-height: 1.5;
        --${prefix}body-color: ${colors.lightMode.gray900};
        --${prefix}body-bg: ${colors.lightMode.white};
        --${prefix}border-width: 1px;
        --${prefix}border-style: solid;
        --${prefix}border-color: ${colors.lightMode.gray300};
        --${prefix}border-color-translucent: rgba(0, 0, 0, 0.175);
        --${prefix}border-radius: 0.375rem;
        --${prefix}border-radius-sm: 0.25rem;
        --${prefix}border-radius-lg: 0.5rem;
        --${prefix}border-radius-xl: 1rem;
        --${prefix}border-radius-2xl: 2rem;
        --${prefix}border-radius-pill: 50rem;
        --${prefix}link-color: ${colors.lightMode.success};
        --${prefix}link-hover-color: #13967d;
        --${prefix}code-color: ${colors.lightMode.pink};
        --${prefix}highlight-bg: #fdebd0;
        --${prefix}primary-btn-text: ${colors.lightMode.white};
        --${prefix}secondary-btn-text: ${colors.lightMode.white};
        --${prefix}success-btn-text: ${colors.lightMode.white};
        --${prefix}info-btn-text: ${colors.lightMode.white};
        --${prefix}warning-btn-text: ${colors.lightMode.white};
        --${prefix}danger-btn-text: ${colors.lightMode.white};
        --${prefix}light-btn-text: ${colors.lightMode.black};
        --${prefix}dark-btn-text: ${colors.lightMode.white};
        --${prefix}input-color: ${colors.lightMode.gray900};
        --${prefix}input-border-color: ${colors.lightMode.gray400};
        --${prefix}input-outline-color: rgba(${colors.lightMode.infoRgb}, 0.30);
    }
    [data-theme="dark"] {
        --${prefix}blue: ${colors.darkMode.blue};
        --${prefix}indigo: ${colors.darkMode.indigo};
        --${prefix}purple: ${colors.darkMode.purple};
        --${prefix}pink: ${colors.darkMode.pink};
        --${prefix}red: ${colors.darkMode.red};
        --${prefix}orange: ${colors.darkMode.orange};
        --${prefix}yellow: ${colors.darkMode.yellow};
        --${prefix}green: ${colors.darkMode.green};
        --${prefix}teal: ${colors.darkMode.teal};
        --${prefix}cyan: ${colors.darkMode.cyan};
        --${prefix}black: ${colors.darkMode.black};
        --${prefix}white: ${colors.darkMode.white};
        --${prefix}gray: ${colors.darkMode.gray};
        --${prefix}gray-dark: ${colors.darkMode.grayDark};
        --${prefix}gray-100: ${colors.darkMode.gray100};
        --${prefix}gray-200: ${colors.darkMode.gray200};
        --${prefix}gray-300: ${colors.darkMode.gray300};
        --${prefix}gray-400: ${colors.darkMode.gray400};
        --${prefix}gray-500: ${colors.darkMode.gray500};
        --${prefix}gray-600: ${colors.darkMode.gray600};
        --${prefix}gray-700: ${colors.darkMode.gray700};
        --${prefix}gray-800: ${colors.darkMode.gray800};
        --${prefix}gray-900: ${colors.darkMode.gray900};
        --${prefix}primary: ${colors.darkMode.primary};
        --${prefix}primary-light: ${hexToHSL(colors.darkMode.primary, 40)};
        --${prefix}primary-dark: ${hexToHSL(colors.darkMode.primary, -7)};
        --${prefix}secondary: ${colors.darkMode.secondary};
        --${prefix}secondary-light: ${hexToHSL(colors.darkMode.secondary, 40)};
        --${prefix}secondary-dark: ${hexToHSL(colors.darkMode.secondary, -7)};
        --${prefix}success: ${colors.darkMode.success};
        --${prefix}success-light: ${hexToHSL(colors.darkMode.success, 40)};
        --${prefix}success-dark: ${hexToHSL(colors.darkMode.success, -7)};
        --${prefix}info: ${colors.darkMode.info};
        --${prefix}info-light: ${hexToHSL(colors.darkMode.info, 30)};
        --${prefix}info-dark: ${hexToHSL(colors.darkMode.info, -7)};
        --${prefix}warning: ${colors.darkMode.warning};
        --${prefix}warning-light: ${hexToHSL(colors.darkMode.warning, 30)};
        --${prefix}warning-dark: ${hexToHSL(colors.darkMode.warning, -7)};
        --${prefix}danger: ${colors.darkMode.danger};
        --${prefix}danger-light: ${hexToHSL(colors.darkMode.danger, 20)};
        --${prefix}danger-dark: ${hexToHSL(colors.darkMode.danger, -10)};
        --${prefix}light: ${colors.darkMode.light};
        --${prefix}light-light: ${hexToHSL(colors.darkMode.light, 20)};
        --${prefix}light-dark: ${hexToHSL(colors.darkMode.light, -7)};
        --${prefix}dark: ${colors.darkMode.dark};
        --${prefix}dark-light: ${hexToHSL(colors.darkMode.dark, 40)};
        --${prefix}dark-dark: ${hexToHSL(colors.darkMode.dark, -7)};
        --${prefix}primary-rgb: ${colors.darkMode.primaryRgb};
        --${prefix}secondary-rgb: ${colors.darkMode.secondaryRgb};
        --${prefix}success-rgb: ${colors.darkMode.successRgb};
        --${prefix}info-rgb: ${colors.darkMode.infoRgb};
        --${prefix}warning-rgb: ${colors.darkMode.warningRgb};
        --${prefix}danger-rgb: ${colors.darkMode.dangerRgb};
        --${prefix}light-rgb: ${colors.darkMode.lightRgb};
        --${prefix}dark-rgb: ${colors.darkMode.darkRgb};
        --${prefix}white-rgb: ${colors.darkMode.whiteRgb};
        --${prefix}black-rgb: ${colors.darkMode.blackRgb};
        --${prefix}body-color-rgb: ${colors.darkMode.bodyColorRgb};
        --${prefix}body-bg-rgb: ${colors.darkMode.bodyBgRgb};
        --${prefix}body-color: ${colors.darkMode.white};
        --${prefix}body-bg: ${colors.darkMode.gray900};
        --${prefix}border-color: ${colors.darkMode.gray300};
        --${prefix}link-color: ${colors.darkMode.success};
        --${prefix}code-color: ${colors.darkMode.pink};
        --${prefix}light-btn-text: ${colors.lightMode.white};
        --${prefix}input-color: ${colors.darkMode.dark};
        --${prefix}input-border-color: ${colors.darkMode.gray900};
        --${prefix}input-outline-color: rgba(${colors.darkMode.infoRgb}, 0.85);
        }
`;

export default styles;
